---
# tasks file for cni-config

- name: Create /etc/cni/net.d directory
  file:
    state: directory
    path: /etc/cni/net.d/
    owner: root
    group: root
    mode: '0755'

- name: Copy CNI configuration onto calico nodes
  template:
    src: templates/10-calico.conflist.j2
    dest: /etc/cni/net.d/10-calico.conflist
    owner: root
    group: root
    mode: '0664'