---
#- name: Execute common tasks on all nodes
#  import_playbook: common.yml

- name: Execute etcd installation tasks on all etcd nodes
  import_playbook: etcd_install.yml

- name: Execute calico installation tasks on calico nodes
  import_playbook: calico_install.yml
