---
#- name: Execute common tasks on all nodes
#  import_playbook: common.yml

- name: Execute package installation tasks on all nodes
  import_playbook: package_install.yml

#- name: Execute roles on all servers
#  hosts: all
#  become: yes
#  roles:
#    - common
#    - package-install