---
- name: Execute common tasks on all nodes
  import_playbook: common.yml

- name: Execute ansible-go-master installation tasks on all nodes
  import_playbook: ansible-go.yml

- name: Execute etcd installation tasks on all etcd nodes
  import_playbook: etcd_install.yml

- name: Execute calico installation tasks on calico nodes
  import_playbook: calico_install.yml

- name: Execute CNI configuration file tasks on calico nodes
  import_playbook: cni_config.yml