---
# tasks file for calico-install

- name: Pull calico-{{ calico_version }} docker image 
  docker_image:
    source: pull
    name: "quay.io/calico/node:{{ calico_version }}"

- name: Run calico-{{ calico_version }} docker image
  docker_container:
    name: "calico-{{ calico_version }}"
    state: started
    network_mode: host
    privileged: yes
    image: "quay.io/calico/node:{{ calico_version }}"
    #auto_remove: true
    volumes:
      - /var/log/calico:/var/log/calico
      - /run/docker/plugins:/run/docker/plugins
      - /lib/modules:/lib/modules
      - /var/run/calico:/var/run/calico
      - /var/lib/calico:/var/lib/calico
    env:
      IP: "{{ hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address'] }}"
      CALICO_NETWORKING_BACKEND: "{{ calico_backend }}"
      NO_DEFAULT_POOLS: "true"
      CALICO_LIBNETWORK_ENABLED: "false"
      ETCD_ENDPOINTS: "http://{{ etcd_ip }}:2379"

- name: Create calico binary location
  file:
    state: directory
    path: /opt/cni/bin/
    owner: root
    group: root
    mode: '0755'

- name: Download the calico CNI plugin binary
  get_url:
    url: https://github.com/projectcalico/cni-plugin/releases/download/v3.14.0/calico-amd64
    dest: /opt/cni/bin/calico
    mode: '0755'
  
- name: Download the calico-ipam CNI plugin binary
  get_url:
    url: https://github.com/projectcalico/cni-plugin/releases/download/v3.14.0/calico-ipam-amd64
    dest: /opt/cni/bin/calico-ipam
    mode: '0755'

#- name: Download Golang installer
#  get_url:
#    url: https://storage.googleapis.com/golang/getgo/installer_linux
#    dest: /tmp/installer_linux
#    mode: '0755'
#
#- name: Run Golang installer 
#  command: 
#    cmd: /tmp/installer_linux 
#    creates: /root/go_installed
#  register: go_installation
#
#- name: Create /root/go_installed file 
#  file:
#    state: touch
#    dest: /root/go_installed 
#    owner: root
#    group: root
#    mode: '0664'
#  when: not go_installation.failed
