---
# tasks file for common

- name: Update apt
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 7200

- name: Install packages
  apt:
    name: ntp docker.io bridge-utils cgroupfs-mount containerd docker.io pigz runc ubuntu-fan
    state: latest 
