---
# tasks file for common

- name: Update apt
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 7200

- name: Install packages
  apt:
    name: "{{ default_packages }}"
    state: latest 