---
# tasks file for common

- name: Update apt
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 7200

- name: Install NTP
  apt:
    name: ntp 
    state: latest 

- name: Install docker
  apt:
    name: docker
    state: latest